# Generated by Django 4.2.5 on 2025-02-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Impresso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
